id: P004486
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 11:26:05.326438
source_metadata:
  id: bdr:W28970
  title: བོད་ཀྱི་དམངས་ཁྲོད་རྩོམ་རིག་སྤྱི་བཤད་བློ་གསར་འདྲེན་པའི་སྐྱ་རེངས
  author: ''
  volumes:
    227c505cd8e34410aa08c0047fb06ba5:
      image_group_id: I5772
      title: ''
      volume_number: 1
      total_pages: 518
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
