id: I979E5E47
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T05:45:09+00:00'
last_modified: '2022-06-08T01:25:38.226377+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W28970
  title: བོད་ཀྱི་དམངས་ཁྲོད་རྩོམ་རིག་སྤྱི་བཤད་བློ་གསར་འདྲེན་པའི་སྐྱ་རེངས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    A9A1:
      image_group_id: I5772
      title: ''
      total_pages: 518
      order: 1
      base_file: A9A1.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
